package uml.hibernate;

// Generated 2012-6-16 9:24:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Booker generated by hbm2java
 */
public class Booker implements java.io.Serializable {

	private Integer bookerid;
	private String cellphone;
	private String name;
	private Set bookingBills = new HashSet(0);

	public Booker() {
	}

	public Booker(String cellphone, String name, Set bookingBills) {
		this.cellphone = cellphone;
		this.name = name;
		this.bookingBills = bookingBills;
	}

	public Integer getBookerid() {
		return this.bookerid;
	}

	public void setBookerid(Integer bookerid) {
		this.bookerid = bookerid;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBookingBills() {
		return this.bookingBills;
	}

	public void setBookingBills(Set bookingBills) {
		this.bookingBills = bookingBills;
	}

}
