package uml.hibernate;

// Generated 2012-6-16 9:24:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BookingBill generated by hbm2java
 */
public class BookingBill implements java.io.Serializable {

	private Integer bookingid;
	private Booker booker;
	private Date bookTime;
	private String bookingPeriod;
	private Date preArrivalTime;
	private Float proDeposit;
	private String feedback;
	private String state;
	private Date cancelTime;
	private Set bookTables = new HashSet(0);

	public BookingBill() {
	}

	public BookingBill(Booker booker, Date bookTime, String bookingPeriod,
			String state) {
		this.booker = booker;
		this.bookTime = bookTime;
		this.bookingPeriod = bookingPeriod;
		this.state = state;
	}

	public BookingBill(Booker booker, Date bookTime, String bookingPeriod,
			Date preArrivalTime, Float proDeposit, String feedback,
			String state, Date cancelTime, Set bookTables) {
		this.booker = booker;
		this.bookTime = bookTime;
		this.bookingPeriod = bookingPeriod;
		this.preArrivalTime = preArrivalTime;
		this.proDeposit = proDeposit;
		this.feedback = feedback;
		this.state = state;
		this.cancelTime = cancelTime;
		this.bookTables = bookTables;
	}

	public Integer getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(Integer bookingid) {
		this.bookingid = bookingid;
	}

	public Booker getBooker() {
		return this.booker;
	}

	public void setBooker(Booker booker) {
		this.booker = booker;
	}

	public Date getBookTime() {
		return this.bookTime;
	}

	public void setBookTime(Date bookTime) {
		this.bookTime = bookTime;
	}

	public String getBookingPeriod() {
		return this.bookingPeriod;
	}

	public void setBookingPeriod(String bookingPeriod) {
		this.bookingPeriod = bookingPeriod;
	}

	public Date getPreArrivalTime() {
		return this.preArrivalTime;
	}

	public void setPreArrivalTime(Date preArrivalTime) {
		this.preArrivalTime = preArrivalTime;
	}

	public Float getProDeposit() {
		return this.proDeposit;
	}

	public void setProDeposit(Float proDeposit) {
		this.proDeposit = proDeposit;
	}

	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	public Set getBookTables() {
		return this.bookTables;
	}

	public void setBookTables(Set bookTables) {
		this.bookTables = bookTables;
	}

}
