package uml.hibernate;

// Generated 2012-6-24 14:59:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Dinningtable generated by hbm2java
 */
public class Dinningtable implements java.io.Serializable {

	private int tableid;
	private Tablegroup tablegroup;
	private String state;
	private Set walkinBills = new HashSet(0);
	private Set bookTables = new HashSet(0);
	private Set tabledishs = new HashSet(0);

	public Dinningtable() {
	}

	public Dinningtable(int tableid, Tablegroup tablegroup, String state) {
		this.tableid = tableid;
		this.tablegroup = tablegroup;
		this.state = state;
	}

	public Dinningtable(int tableid, Tablegroup tablegroup, String state,
			Set walkinBills, Set bookTables, Set tabledishs) {
		this.tableid = tableid;
		this.tablegroup = tablegroup;
		this.state = state;
		this.walkinBills = walkinBills;
		this.bookTables = bookTables;
		this.tabledishs = tabledishs;
	}

	public int getTableid() {
		return this.tableid;
	}

	public void setTableid(int tableid) {
		this.tableid = tableid;
	}

	public Tablegroup getTablegroup() {
		return this.tablegroup;
	}

	public void setTablegroup(Tablegroup tablegroup) {
		this.tablegroup = tablegroup;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getWalkinBills() {
		return this.walkinBills;
	}

	public void setWalkinBills(Set walkinBills) {
		this.walkinBills = walkinBills;
	}

	public Set getBookTables() {
		return this.bookTables;
	}

	public void setBookTables(Set bookTables) {
		this.bookTables = bookTables;
	}

	public Set getTabledishs() {
		return this.tabledishs;
	}

	public void setTabledishs(Set tabledishs) {
		this.tabledishs = tabledishs;
	}

}
