package uml.hibernate;

// Generated 2012-6-16 9:24:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productid;
	private Unitgroup unitgroup;
	private Productgroup productgroup;
	private String name;
	private float unitPrice;
	private String jinpin;
	private int currentInventory;
	private Set tabledishs = new HashSet(0);

	public Product() {
	}

	public Product(String name, float unitPrice, String jinpin,
			int currentInventory) {
		this.name = name;
		this.unitPrice = unitPrice;
		this.jinpin = jinpin;
		this.currentInventory = currentInventory;
	}

	public Product(Unitgroup unitgroup, Productgroup productgroup, String name,
			float unitPrice, String jinpin, int currentInventory, Set tabledishs) {
		this.unitgroup = unitgroup;
		this.productgroup = productgroup;
		this.name = name;
		this.unitPrice = unitPrice;
		this.jinpin = jinpin;
		this.currentInventory = currentInventory;
		this.tabledishs = tabledishs;
	}

	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	public Unitgroup getUnitgroup() {
		return this.unitgroup;
	}

	public void setUnitgroup(Unitgroup unitgroup) {
		this.unitgroup = unitgroup;
	}

	public Productgroup getProductgroup() {
		return this.productgroup;
	}

	public void setProductgroup(Productgroup productgroup) {
		this.productgroup = productgroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(float unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getJinpin() {
		return this.jinpin;
	}

	public void setJinpin(String jinpin) {
		this.jinpin = jinpin;
	}

	public int getCurrentInventory() {
		return this.currentInventory;
	}

	public void setCurrentInventory(int currentInventory) {
		this.currentInventory = currentInventory;
	}

	public Set getTabledishs() {
		return this.tabledishs;
	}

	public void setTabledishs(Set tabledishs) {
		this.tabledishs = tabledishs;
	}

}
