package uml.hibernate;

// Generated 2012-6-16 9:24:29 by Hibernate Tools 3.4.0.CR1

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private Integer staffid;
	private String name;
	private String password;
	private String flag;

	public Staff() {
	}

	public Staff(String name, String flag) {
		this.name = name;
		this.flag = flag;
	}

	public Staff(String name, String password, String flag) {
		this.name = name;
		this.password = password;
		this.flag = flag;
	}

	public Integer getStaffid() {
		return this.staffid;
	}

	public void setStaffid(Integer staffid) {
		this.staffid = staffid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
