package uml.hibernate;

// Generated 2012-6-16 9:24:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tablegroup generated by hbm2java
 */
public class Tablegroup implements java.io.Serializable {

	private Integer tablecateid;
	private String category;
	private int containNumber;
	private float lowestConsumption;
	private Set dinningtables = new HashSet(0);

	public Tablegroup() {
	}

	public Tablegroup(String category, int containNumber,
			float lowestConsumption) {
		this.category = category;
		this.containNumber = containNumber;
		this.lowestConsumption = lowestConsumption;
	}

	public Tablegroup(String category, int containNumber,
			float lowestConsumption, Set dinningtables) {
		this.category = category;
		this.containNumber = containNumber;
		this.lowestConsumption = lowestConsumption;
		this.dinningtables = dinningtables;
	}

	public Integer getTablecateid() {
		return this.tablecateid;
	}

	public void setTablecateid(Integer tablecateid) {
		this.tablecateid = tablecateid;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public int getContainNumber() {
		return this.containNumber;
	}

	public void setContainNumber(int containNumber) {
		this.containNumber = containNumber;
	}

	public float getLowestConsumption() {
		return this.lowestConsumption;
	}

	public void setLowestConsumption(float lowestConsumption) {
		this.lowestConsumption = lowestConsumption;
	}

	public Set getDinningtables() {
		return this.dinningtables;
	}

	public void setDinningtables(Set dinningtables) {
		this.dinningtables = dinningtables;
	}

}
