package uml.hibernate;

// Generated 2012-6-26 17:05:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Waiter generated by hbm2java
 */
public class Waiter implements java.io.Serializable {

	private int waiterid;
	private Waitergroup waitergroup;
	private String name;
	private String sex;
	private String cellphone;
	private String cid;
	private Date salarydate;

	public Waiter() {
	}

	public Waiter(int waiterid, Waitergroup waitergroup, String name,
			String sex, String cellphone, String cid, Date salarydate) {
		this.waiterid = waiterid;
		this.waitergroup = waitergroup;
		this.name = name;
		this.sex = sex;
		this.cellphone = cellphone;
		this.cid = cid;
		this.salarydate = salarydate;
	}

	public int getWaiterid() {
		return this.waiterid;
	}

	public void setWaiterid(int waiterid) {
		this.waiterid = waiterid;
	}

	public Waitergroup getWaitergroup() {
		return this.waitergroup;
	}

	public void setWaitergroup(Waitergroup waitergroup) {
		this.waitergroup = waitergroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public Date getSalarydate() {
		return this.salarydate;
	}

	public void setSalarydate(Date salarydate) {
		this.salarydate = salarydate;
	}

}
