package uml.hibernate;

// Generated 2012-6-24 15:03:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WalkinBill generated by hbm2java
 */
public class WalkinBill implements java.io.Serializable {

	private Integer walkinid;
	private Dinningtable dinningtable;
	private int peopleNumber;
	private String feedback;
	private Date date;
	private String state;

	public WalkinBill() {
	}

	public WalkinBill(Dinningtable dinningtable, int peopleNumber, Date date,
			String state) {
		this.dinningtable = dinningtable;
		this.peopleNumber = peopleNumber;
		this.date = date;
		this.state = state;
	}

	public WalkinBill(Dinningtable dinningtable, int peopleNumber,
			String feedback, Date date, String state) {
		this.dinningtable = dinningtable;
		this.peopleNumber = peopleNumber;
		this.feedback = feedback;
		this.date = date;
		this.state = state;
	}

	public Integer getWalkinid() {
		return this.walkinid;
	}

	public void setWalkinid(Integer walkinid) {
		this.walkinid = walkinid;
	}

	public Dinningtable getDinningtable() {
		return this.dinningtable;
	}

	public void setDinningtable(Dinningtable dinningtable) {
		this.dinningtable = dinningtable;
	}

	public int getPeopleNumber() {
		return this.peopleNumber;
	}

	public void setPeopleNumber(int peopleNumber) {
		this.peopleNumber = peopleNumber;
	}

	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
